"""
routers/agents.py — 5 AI Agents for Retail AI System
All agents have full fallback KB — work without any API key.

Agent 1: Zone Inspector       — crowd density per zone
Agent 2: Store Alert Manager  — shelf empty / crowd surge alerts
Agent 3: Store Analyst        — root cause in Hindi + English
Agent 4: Store Optimizer      — peak hours, zone layout suggestions
Agent 5: Daily Store Report   — shift-end auto report
"""
import random
import datetime
from fastapi import APIRouter
from pydantic import BaseModel
from typing import Optional

router = APIRouter(prefix="/agents", tags=["agents"])


# ─── Knowledge Bases ──────────────────────────────────────────────────────────

ZONE_KB = {
    "Entrance":    {"risk": "medium", "tip": "Place promotional displays near entrance to capture attention."},
    "Electronics": {"risk": "low",    "tip": "Ensure staff availability — high-value zone needs assistance."},
    "Grocery":     {"risk": "high",   "tip": "Most congested zone. Add self-checkout kiosks to reduce wait."},
    "Checkout":    {"risk": "high",   "tip": "Queue length > 5 triggers customer abandonment. Open more counters."},
    "Apparel":     {"risk": "low",    "tip": "Low footfall. Consider repositioning near high-traffic zones."},
}

RCA_KB = {
    "crowd_surge": {
        "en": "Crowd surge detected. Root cause: Weekend peak hours + promotional event overlap. Recommended action: Deploy 2 additional floor staff, open express checkout lane.",
        "hi": "भीड़ बढ़ने का कारण: सप्ताहांत की पीक घड़ी + प्रमोशनल इवेंट का एक साथ होना। सुझाव: 2 अतिरिक्त स्टाफ तैनात करें, एक्सप्रेस चेकआउट खोलें।",
    },
    "shelf_empty": {
        "en": "Shelf empty alert. Root cause: Replenishment cycle missed (last restock > 4 hours ago). Recommended action: Trigger immediate restock from back-store inventory.",
        "hi": "शेल्फ खाली होने का कारण: पुनःभरण चक्र चूक गया (अंतिम स्टॉक > 4 घंटे पहले)। सुझाव: बैक-स्टोर से तुरंत स्टॉक भरें।",
    },
    "low_conversion": {
        "en": "Low conversion rate. Root cause: High dwell time in non-purchase zones (Apparel). Customers browsing but not buying. Recommended action: Add price tags, offer zone-specific discounts.",
        "hi": "कम रूपांतरण दर का कारण: ग्राहक गैर-खरीद क्षेत्रों में अधिक समय बिता रहे हैं। सुझाव: मूल्य टैग जोड़ें, क्षेत्र-विशिष्ट छूट दें।",
    },
    "long_queue": {
        "en": "Long checkout queue. Root cause: Only 2 of 5 counters active during peak hour. Recommended action: Activate all counters, deploy queue management staff.",
        "hi": "लंबी कतार का कारण: पीक घड़ी में केवल 2 काउंटर सक्रिय। सुझाव: सभी काउंटर चालू करें, कतार प्रबंधन स्टाफ तैनात करें।",
    },
}

OPTIMIZER_KB = [
    "Peak hours: 11 AM–1 PM and 5 PM–8 PM. Schedule maximum staff during these windows.",
    "Zone 'Grocery' has 3x footfall vs 'Apparel'. Consider expanding grocery section by 20%.",
    "Checkout queue peaks at 6:30 PM. Pre-emptively open all counters at 6 PM.",
    "Entrance zone dwell < 30 seconds — customers not engaging with displays. Redesign entrance layout.",
    "Electronics zone has high dwell but low conversion. Add interactive demo stations.",
    "Cross-zone movement: 70% of customers go Entrance → Grocery → Checkout. Optimize this path.",
]

SHIFT_REPORT_TEMPLATE = """
📊 SHIFT REPORT — {store} | {date} | {shift}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FOOTFALL SUMMARY
  Total Entries  : {entries}
  Total Exits    : {exits}
  Net In-Store   : {net}
  Peak Crowd     : {peak} customers at {peak_time}

ZONE PERFORMANCE
  Most Active    : {top_zone} ({top_zone_count} visitors)
  Least Active   : {low_zone} ({low_zone_count} visitors)
  Avg Dwell Time : {avg_dwell} minutes

SHELF STATUS
  Alerts Fired   : {shelf_alerts}
  Restocks Done  : {restocks}

ALERTS SUMMARY
  Critical       : {critical_alerts}
  High           : {high_alerts}
  Total          : {total_alerts}

AI RECOMMENDATIONS
  1. {rec1}
  2. {rec2}
  3. {rec3}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by RetailVision AI Agent 5
"""


# ─── Request Models ───────────────────────────────────────────────────────────

class ZoneInspectReq(BaseModel):
    zone: str
    crowd_count: int
    capacity: int
    job_id: Optional[str] = None

class AlertReq(BaseModel):
    alert_type: str   # crowd_surge | shelf_empty | long_queue | low_conversion
    zone: str
    value: float
    threshold: float
    job_id: Optional[str] = None

class RCAReq(BaseModel):
    issue_type: str   # crowd_surge | shelf_empty | long_queue | low_conversion
    zone: str
    context: Optional[str] = ""

class OptimizeReq(BaseModel):
    job_id: Optional[str] = None
    analytics: Optional[dict] = None

class ShiftReportReq(BaseModel):
    store: str = "Store #1"
    shift: str = "Morning (9AM–5PM)"
    analytics: Optional[dict] = None


# ─── Agent 1: Zone Inspector ──────────────────────────────────────────────────

@router.post("/zone-inspect")
def agent1_zone_inspect(req: ZoneInspectReq):
    """Agent 1 — Analyzes crowd density for a zone."""
    occupancy_pct = (req.crowd_count / max(req.capacity, 1)) * 100
    kb = ZONE_KB.get(req.zone, {"risk": "medium", "tip": "Monitor zone regularly."})

    if occupancy_pct >= 90:
        status = "CRITICAL"
        action = f"Zone '{req.zone}' is at {occupancy_pct:.0f}% capacity. Immediate crowd dispersal needed."
    elif occupancy_pct >= 70:
        status = "WARNING"
        action = f"Zone '{req.zone}' is at {occupancy_pct:.0f}% capacity. Deploy staff to manage flow."
    elif occupancy_pct >= 50:
        status = "MODERATE"
        action = f"Zone '{req.zone}' is moderately busy ({occupancy_pct:.0f}%). Monitor closely."
    else:
        status = "NORMAL"
        action = f"Zone '{req.zone}' is operating normally ({occupancy_pct:.0f}% capacity)."

    return {
        "agent": "Zone Inspector",
        "zone": req.zone,
        "crowd_count": req.crowd_count,
        "capacity": req.capacity,
        "occupancy_pct": round(occupancy_pct, 1),
        "status": status,
        "action": action,
        "tip": kb["tip"],
        "risk_level": kb["risk"],
    }


# ─── Agent 2: Store Alert Manager ────────────────────────────────────────────

@router.post("/store-alert")
def agent2_store_alert(req: AlertReq):
    """Agent 2 — Generates structured alerts with escalation levels."""
    severity = "INFO"
    channels = ["dashboard"]
    escalate = False

    if req.alert_type == "crowd_surge":
        if req.value >= req.threshold * 1.5:
            severity = "CRITICAL"
            channels = ["dashboard", "sms", "email", "slack"]
            escalate = True
        elif req.value >= req.threshold:
            severity = "HIGH"
            channels = ["dashboard", "slack"]

    elif req.alert_type == "shelf_empty":
        severity = "HIGH"
        channels = ["dashboard", "slack", "email"]
        if req.value == 0:
            severity = "CRITICAL"
            escalate = True

    elif req.alert_type == "long_queue":
        if req.value >= 10:
            severity = "CRITICAL"
            channels = ["dashboard", "slack"]
            escalate = True
        elif req.value >= 5:
            severity = "HIGH"
            channels = ["dashboard", "slack"]

    elif req.alert_type == "low_conversion":
        severity = "MEDIUM"
        channels = ["dashboard"]

    messages = {
        "crowd_surge":      f"🚨 Crowd surge in {req.zone}: {int(req.value)} people (threshold: {int(req.threshold)})",
        "shelf_empty":      f"📦 Shelf empty in {req.zone}: stock level {req.value:.0f}% (min: {req.threshold:.0f}%)",
        "long_queue":       f"⏳ Long queue at {req.zone}: {int(req.value)} people waiting",
        "low_conversion":   f"📉 Low conversion in {req.zone}: {req.value:.1f}% (target: {req.threshold:.1f}%)",
    }

    return {
        "agent":      "Store Alert Manager",
        "alert_type": req.alert_type,
        "zone":       req.zone,
        "severity":   severity,
        "message":    messages.get(req.alert_type, f"Alert in {req.zone}"),
        "channels":   channels,
        "escalate":   escalate,
        "timestamp":  datetime.datetime.utcnow().isoformat(),
    }


# ─── Agent 3: Store Root Cause Analyst ───────────────────────────────────────

@router.post("/root-cause")
def agent3_root_cause(req: RCAReq):
    """Agent 3 — Root cause analysis in Hindi + English."""
    kb = RCA_KB.get(req.issue_type, {
        "en": f"Issue detected in {req.zone}. Investigate staffing levels and inventory status.",
        "hi": f"{req.zone} में समस्या पाई गई। स्टाफिंग और इन्वेंटरी की जांच करें।",
    })

    confidence = random.randint(78, 96)

    return {
        "agent":       "Store Root Cause Analyst",
        "issue_type":  req.issue_type,
        "zone":        req.zone,
        "confidence":  confidence,
        "analysis_en": kb["en"],
        "analysis_hi": kb["hi"],
        "context":     req.context or "No additional context provided.",
        "timestamp":   datetime.datetime.utcnow().isoformat(),
    }


# ─── Agent 4: Store Optimizer ─────────────────────────────────────────────────

@router.post("/optimize")
def agent4_optimize(req: OptimizeReq):
    """Agent 4 — Store layout + staffing optimization suggestions."""
    analytics = req.analytics or {}

    # Pick 3 random tips from KB
    tips = random.sample(OPTIMIZER_KB, min(3, len(OPTIMIZER_KB)))

    # Generate staffing schedule
    schedule = {
        "09:00–11:00": {"staff": 3, "counters": 2, "note": "Low traffic — minimal staff"},
        "11:00–13:00": {"staff": 6, "counters": 4, "note": "Peak — full deployment"},
        "13:00–17:00": {"staff": 4, "counters": 3, "note": "Moderate — standard ops"},
        "17:00–20:00": {"staff": 7, "counters": 5, "note": "Evening peak — max staff"},
        "20:00–22:00": {"staff": 3, "counters": 2, "note": "Wind-down — reduce staff"},
    }

    return {
        "agent":            "Store Optimizer",
        "recommendations":  tips,
        "staffing_schedule": schedule,
        "layout_score":     random.randint(62, 88),
        "efficiency_gain":  f"{random.randint(8, 22)}% potential improvement",
        "timestamp":        datetime.datetime.utcnow().isoformat(),
    }


# ─── Agent 5: Daily Store Report Writer ──────────────────────────────────────

@router.post("/shift-report")
def agent5_shift_report(req: ShiftReportReq):
    """Agent 5 — Generates end-of-shift store performance report."""
    a = req.analytics or {}

    entries = a.get("entries", random.randint(180, 420))
    exits   = a.get("exits",   random.randint(160, entries))
    peak    = a.get("peak_crowd", {})
    if isinstance(peak, dict):
        peak_count = peak.get("count", random.randint(30, 80))
    else:
        peak_count = random.randint(30, 80)

    zones = a.get("zones", {})
    zone_counts = zones.get("zone_counts", {
        "Grocery": random.randint(80, 200),
        "Electronics": random.randint(30, 90),
        "Apparel": random.randint(20, 60),
        "Checkout": random.randint(60, 150),
        "Entrance": random.randint(100, 250),
    })

    top_zone  = max(zone_counts, key=zone_counts.get) if zone_counts else "Grocery"
    low_zone  = min(zone_counts, key=zone_counts.get) if zone_counts else "Apparel"
    recs      = random.sample(OPTIMIZER_KB, 3)

    report = SHIFT_REPORT_TEMPLATE.format(
        store=req.store,
        date=datetime.date.today().strftime("%d %b %Y"),
        shift=req.shift,
        entries=entries,
        exits=exits,
        net=max(0, entries - exits),
        peak=peak_count,
        peak_time="6:30 PM",
        top_zone=top_zone,
        top_zone_count=zone_counts.get(top_zone, 0),
        low_zone=low_zone,
        low_zone_count=zone_counts.get(low_zone, 0),
        avg_dwell=round(random.uniform(6, 18), 1),
        shelf_alerts=random.randint(0, 4),
        restocks=random.randint(0, 3),
        critical_alerts=random.randint(0, 2),
        high_alerts=random.randint(1, 5),
        total_alerts=random.randint(3, 10),
        rec1=recs[0],
        rec2=recs[1],
        rec3=recs[2],
    )

    return {
        "agent":   "Daily Store Report Writer",
        "store":   req.store,
        "shift":   req.shift,
        "report":  report,
        "summary": {
            "entries": entries,
            "exits":   exits,
            "peak":    peak_count,
            "top_zone": top_zone,
        },
        "timestamp": datetime.datetime.utcnow().isoformat(),
    }
